# Generated by Django 3.2.9 on 2021-12-07 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('patientName', models.CharField(max_length=200)),
                ('patientSurname', models.CharField(max_length=200)),
                ('patientEmail', models.CharField(max_length=200)),
                ('patientPassword', models.CharField(max_length=200)),
                ('patientCreateTime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
