# Generated by Django 3.2.9 on 2021-12-18 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentTime', models.DateTimeField()),
                ('appointmentPoint', models.CharField(max_length=200, null=True)),
                ('appointmentDepartmanID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.departman')),
                ('appointmentDoctorID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.doctor')),
                ('appointmentPatientID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.patient')),
            ],
        ),
    ]
