# Generated by Django 3.2.9 on 2021-12-11 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorScore',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
