# Generated by Django 3.2.9 on 2021-12-26 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientSex',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
