# Generated by Django 4.0 on 2021-12-31 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0002_patient_patientsex'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='countOfRating',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
