# Generated by Django 3.2.9 on 2021-12-15 00:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0002_doctor_doctorscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorSex',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentPoint', models.CharField(max_length=200, null=True)),
                ('appointmentDepartmanID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.departman')),
                ('appointmentDoctorID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.doctor')),
                ('appointmentPatientID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentApp.patient')),
            ],
        ),
    ]
