# Generated by Django 4.0 on 2021-12-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentApp', '0003_doctor_countofrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='countOfRating',
            field=models.IntegerField(null=True),
        ),
    ]
